# Data
url=file:///C:/Users/JonathanSaddler/Code/tryout/java/selenium-example2/PracticeTestWebsite/practice-test-alertcal/index.html
#doctor_name=Dr. Sunil Kumar N.K.
doctor_name=Dr. Rajendra S Gujjalanawar
patient_name=Jonathan Saddler
patient_email=abc@gmail.com
patient_mobile=5554329876
dob=12-12-2005
appointment1_date=12-07-2024
UHID=606700051221
appointment1_date=20-06-2026
UHID=60670051221

# Data
Consultation_btn=Consultation
name_id=req_name
email_id=req_email
mobile_id=req_mobile

# Locators
# 2nd test locators
doctorverification_xpath=//*[@title='Dr. Manjunath Malige']
displayDate_id=monthYearTitle

displayDate_xpath=//*[@class='pickadate-header']/h3
allDates_xapth=//*[@ng-click='setDate(d)']
nextWeek_xpath=//*[@ng-show='allowNextMonth']
gotoAppointment_id=gotoLogin
mobileNumber_xpath=//*[@name='mobile_number']
continue_xpath=//*[@class='form-group5']/div/button
cancelPopUp_xpath=//*[@ng-click='psuno()']
titleDropdown_id=salutation
firstName=first_name
lastName_xpath=//*[@ng-model='user.last_name']
dob_id=dob
state_id=state
city_id=city

# my new locators
uhid_id=uhid1   
calendarPreferDate1_id=prefDate1
calendarPreferDate2_id=prefDate2
radioBtnYes_id=registered1-yes
radioBtnNo_id=registered1-no
# Data
doctor_name=Dr. Sunil Kumar N.K.
patient_name=Anshul Chauhan
patient_email=abc@gmail.com
patient_mobile=9716180700

# Data for Second Test
OnDemandDoctor=Dr. Manjunath Malige
nameTitle=Dr.
firstName=Jonathan
lastName=Saddler
StateName=OH
CityName=Cincinnati


# my new locators for Second Test
displayDate_id=monthYearTitle

allDates_xpath=//div[@id="calendar1"]//td
nextWeek_xpath=//*[@id='nextMonthBtn']
title_id=selTitle
firstName_id=txtFirstName
middleName_id=txtMiddleName
lastName_id=txtLastName
email_id=txtEmail
dob_id=txtDob
country_id=selCountry
state_id=selState
dobCalendarYear_xpath=//*[@class='ui-datepicker-year'][@data-handler='selectYear']
dobCalendarMonth_xpath=//*[@class='ui-datepicker-month'][@data-handler='selectMonth']