# Data
url=https://www.sakraworldhospital.com/request-appointment
#doctor_name=Dr. Sunil Kumar N.K.
doctor_name=Dr. Rajendra S Gujjalanawar
patient_name=Jonathan Saddler
patient_email=abc@gmail.com
patient_mobile=5554329876
dob=12-12-2005
appointment1_date=12-07-2024
UHID=606700051221

# Data
Consultation_btn=Consultation
name_id=req_name
email_id=req_email
mobile_id=req_mobile

# More Locators
doctorverification_xpath=//*[@title='Dr. Manjunath Malige']
displayDate_xpath=//*[@class='pickadate-header']/h3
allDates_xapth=//*[@ng-click='setDate(d)']
nextWeek_xpath=//*[@ng-show='allowNextMonth']
gotoAppointment_id=gotoLogin
mobileNumber_xpath=//*[@name='mobile_number']
continue_xpath=//*[@class='form-group5']/div/button
cancelPopUp_xpath=//*[@ng-click='psuno()']
titleDropdown_id=salutation
firstName=first_name
lastName_xpath=//*[@ng-model='user.last_name']
dob_id=dob
state_id=state
city_id=city

# Data
url=https://www.sakraworldhospital.com/request-appointment
doctor_name=Dr. Sunil Kumar N.K.
patient_name=Anshul Chauhan
patient_email=abc@gmail.com
patient_mobile=9716180700


# Data for Second Test
OnDemandDoctor=Dr. Manjunath Malige
nameTitle=Mr.
FirstName=Anshul
LastName=Chauhan
StateName=Uttar Pradesh
CityName=Noida Complex



