GenericKeywords:
openBrowser
click
type
select
getText
navigate
acceptAlert
dismissAlert

ValidationKeywords:
validateTitle
validateText
validateElementPresent
validateElementClickable
validateElementDisplayed

ApplicationKeywords
login
selectDate

